### ISSUE TITLE
caching default values section seems wrong?

### ISSUE THREAD

**Issue by robitnik** [chalk-ai/docs#70]
In the page on caching https://docs.chalk.ai/docs/feature-caching

Should the following:

> In an online environment, all feature values are taken from past runs or historical tables, where max_staleness does not apply.

Not instead say "In an **Offline** environment..."

**Comment by hugokitano** [comment]
That's correct. Thanks for the heads up!

**Comment by hugokitano** [comment]
https://github.com/chalk-ai/docs/pull/71/files <- fix
